apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "part-order-app.orderServiceName" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "part-order-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: part-order-service
data:
  SPRING_PROFILES_ACTIVE: {{ .Values.springProfile | quote }}
  # short in-cluster DNS name for the inventory Service; used directly by
  # the @FeignClient url attribute in InventoryServiceClient
  INVENTORY_SERVICE_URL: "http://{{ include "part-order-app.inventoryServiceName" . }}:{{ .Values.partInventoryService.service.port }}"
  {{- if .Values.mysql.enabled }}
  MYSQL_HOST: {{ include "part-order-app.mysqlName" . | quote }}
  MYSQL_PORT: "3306"
  MYSQL_DATABASE: {{ .Values.mysql.orderDatabase | quote }}
  MYSQL_USER: {{ .Values.mysql.orderUser | quote }}
  {{- end }}
